namespace Game.Shared;

/// <summary>
/// THE cities. Extracted from <see cref="WorldMap"/> for one structural reason: it breaks a static
/// initialisation CYCLE.
///
/// <see cref="WorldMap.SpawnZones"/> is generated by <see cref="WorldPlan"/>, and WorldPlan needs the
/// city centres to place fields around them. With the towns living in WorldMap, that made
/// WorldMap → WorldPlan → WorldMap: whichever type was touched first would run its field initialisers
/// while the other's were still half-done, and read a null array. Which one that was depended on the
/// order some unrelated caller happened to touch them in — the worst possible failure mode.
///
/// Towns depend on nothing, so nothing can be half-initialised beneath them.
/// <see cref="WorldMap.SafeZones"/> still forwards here, so every existing call site is unchanged.
///
/// NOTE: all place names are original/generic on purpose — NEVER reuse town, region or NPC names
/// trademarked by other games.
/// </summary>
public static class Towns
{
    /// <summary>Safe zones (cities/castles): no mobs spawn or enter, aggro clears inside, regen is
    /// boosted. Each has a stable id so teleports can target it. The first is the starter town at the
    /// map centre.
    ///
    /// FIVE cities (owner, 2026-07-29) — Emberfall and Duskvale are gone, their rosters redistributed.
    /// Each owns a level range and 2-3 hunting fields; see <see cref="WorldPlan.Plans"/>.</summary>
    public static readonly SafeZone[] All =
    {
        new("town_brackenford", "Brackenford",     24000, 24000, 3500),   // 1-16
        new("town_stonewatch",  "Stonewatch",      24000, 10000, 2000),   // 16-40
        new("town_greymarsh",   "Greymarsh",       36000, 33000, 2000),   // 40-60
        new("castle_ironreach", "Ironreach Keep",  24000, 38000, 2200),   // 60-75
        new("town_frostmere",   "Frostmere",       12000, 15000, 2000),   // 76-90
        // Small outpost beside the Training Grounds, so you can buff up and teleport out without leaving
        // the dummies. Sits just SOUTH of the dummy row (y=4000, radius 200), clear of them — a safe zone
        // keeps mobs out, and the dummies ARE mobs.
        new("outpost_training", "Training Outpost", 24000, 5000, 400),
        // The Hollow Crypt dungeon ENTRANCE, in the negative quadrant with the dungeon. A safe arrive/
        // regroup spot before the elite rooms just NE of it.
        //
        // GATED TO GREYMARSH. Being a safe zone used to make it a destination from EVERY gatekeeper
        // automatically — so a level-1 in Brackenford was offered a level 44-48 dungeon in the same list
        // as his first hunting field, and the crypt read as one more town rather than as somewhere you
        // earn your way to. The crypt's band (44-48) sits inside Greymarsh's (40-60), so Greymarsh is the
        // door. The gate itself is not one-way: the entrance has no gatekeeper, and you leave the way
        // every dungeon is left — a Scroll of Return, or the halls' own exit.
        new("dungeon_hollow_crypt", "Hollow Crypt", -12000, -12000, 500, GatedByCityId: "town_greymarsh"),
    };

    /// <summary>The STARTER town (map centre). Used where "nearest" would leak information — a player
    /// released from jail is sent here rather than to whatever town happens to be closest, so the jail's
    /// location stays secret.</summary>
    public static SafeZone Starting => All[0];

    public static SafeZone? ById(string id) => System.Array.Find(All, z => z.Id == id);
}
