using System.Linq;

namespace Game.Shared;

/// <summary>
/// THE cities. Extracted from <see cref="WorldMap"/> for one structural reason: it breaks a static
/// initialisation CYCLE.
///
/// <see cref="WorldMap.SpawnZones"/> is generated by <see cref="WorldPlan"/>, and WorldPlan needs the
/// city centres to place fields around them. With the towns living in WorldMap, that made
/// WorldMap → WorldPlan → WorldMap: whichever type was touched first would run its field initialisers
/// while the other's were still half-done, and read a null array. Which one that was depended on the
/// order some unrelated caller happened to touch them in — the worst possible failure mode.
///
/// Towns depend on nothing, so nothing can be half-initialised beneath them.
/// <see cref="WorldMap.SafeZones"/> still forwards here, so every existing call site is unchanged.
///
/// NOTE: all place names are original/generic on purpose — NEVER reuse town, region or NPC names
/// trademarked by other games.
/// </summary>
public static class Towns
{
    /// <summary>Safe zones (cities/castles): no mobs spawn or enter, aggro clears inside, regen is
    /// boosted. Each has a stable id so teleports can target it. The first is the starter town at the
    /// map centre.
    ///
    /// FIVE cities (owner, 2026-07-29) — Emberfall and Duskvale are gone, their rosters redistributed.
    /// Each owns a level range and 2-3 hunting fields; see <see cref="WorldPlan.Plans"/>.</summary>
    public static readonly SafeZone[] All = new[]
    {
        new SafeZone("town_brackenford", "Brackenford",     24000, 24000, 3500),   // 1-16
        new SafeZone("town_stonewatch",  "Stonewatch",      24000, 10000, 2000),   // 16-40
        new SafeZone("town_greymarsh",   "Greymarsh",       36000, 33000, 2000),   // 40-60
        new SafeZone("castle_ironreach", "Ironreach Keep",  24000, 38000, 2200),   // 60-75
        new SafeZone("town_frostmere",   "Frostmere",       12000, 15000, 2000),   // 76-90
        // Small outpost beside the Training Grounds, so you can buff up and teleport out without leaving
        // the dummies. Sits just SOUTH of the dummy row (y=4000, radius 200), clear of them — a safe zone
        // keeps mobs out, and the dummies ARE mobs.
        new SafeZone("outpost_training", "Training Outpost", 24000, 5000, 400, RegenBoost: false),
    }
    // The three dungeon ENTRANCES come from DUNGEONLAYOUT, not from a literal here — the door and the
    // corridor that starts inside it are the same shape, and they were being authored in two files that
    // had to keep agreeing (the crypt's outline began 212 units from a centre written down over here).
    // DungeonLayout depends on nothing, so reading it from Towns cannot rebuild the initialisation cycle
    // this class was extracted to break. Each entrance is gated to the city whose band contains its
    // dungeon's — see DungeonLayout.EntranceZones for why.
    .Concat(DungeonLayout.EntranceZones).ToArray();

    /// <summary>The STARTER town (map centre). Used where "nearest" would leak information — a player
    /// released from jail is sent here rather than to whatever town happens to be closest, so the jail's
    /// location stays secret.</summary>
    public static SafeZone Starting => All[0];

    public static SafeZone? ById(string id) => System.Array.Find(All, z => z.Id == id);
}
